### ISSUE TITLE
Improvements to Buffer

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#19]
* [x] The `BufferWrapper` can probably just store the `usage` parameter, and let the renderer set a sensible default value when the gpu buffer is created.
* [x] Do we expose an API for mapping arrays? See #17 (No, we can't)
* [x] Property to use only a part of the geometry (mapping to `render_pass.draw()`args), see https://github.com/pygfx/pygfx/issues/414#issuecomment-1361006308
* [x] Use a separate buffer subclass for buffers that only live on the GPU?
  * No, but add a flag to buffers that allows us to semantically identify such buffers and make this explicit. This makes it easier to implement property validation, and to triage the kind of buffer in other places in the code.
* [x] Use a separate buffer subclass for uniform buffers, since they have no format?
  * No, but revise the `update_range` method. Let's rename it to `update`. Without arguments it should update the entire buffer. Then the arguments should make it possible to also mark ranges and bitmasks for an update.
  * Optimize the internals to support more fine-grained updates. See #600
* [x] ~Store less attributes on `self._store` since the size won't change (we initially were not sure whether buffer sizes could change).~ -> the reason for using `_store` for constants is that they still "change" from the pipeline's perspective, when a buffer is swapped with another.
* [x] Explain buffers and textures in the Guide in the docs (transferred from #114).
* [x] Support updating the buffer/texture data without copying data (to the `buffer.data` array).
  * Add a `data` property setter to update the data without needing to copy via `buffer.data[:] = other_data` as it is today.
* [x] Can we support other endianness? See #714

Postponed indefinitely until we identify valid use cases:

* [ ] Leverage numpy to define structured arrays and buffer vs view?
* [ ] Support for interleaved buffers (should follow from the above).
* [ ] Explicit properties for `stride` and `element_size`, or use the numpy array for that?

**Comment by almarklein** [comment]
From Slack, how it works in threeJS:
```js
var arrayBuffer = new ArrayBuffer( particles * 16 );

var interleavedFloat32Buffer = new Float32Array( arrayBuffer );
var interleavedUint8Buffer = new Uint8Array( arrayBuffer );

// (this is not needed for non-interleaved buffers)
// InterleavedBuffer( array : TypedArray, stride : Integer )
var interleavedBuffer32 = new THREE.InterleavedBuffer( interleavedFloat32Buffer, 4 );
var interleavedBuffer8 = new THREE.InterleavedBuffer( interleavedUint8Buffer, 16 );

// everything above this line can be done with numpy?

// BufferAttribute( array : TypedArray, itemSize : Integer)
// InterleavedBufferAttribute( interleavedBuffer : InterleavedBuffer, itemSize : Integer, offset : Integer)
geometry.setAttribute( 'position', new THREE.InterleavedBufferAttribute( interleavedBuffer32, 3, 0, false ) );
geometry.setAttribute( 'color', new THREE.InterleavedBufferAttribute( interleavedBuffer8, 3, 12, true ) );
```

**Comment by Korijn** [comment]
I think this is implemented now?

**Comment by almarklein** [comment]
No. I think you're thinking of the uniform buffers which are more or less automated now. But striding for storage/vertex buffers is still to be implemented.

**Comment by almarklein** [comment]
Note: the last point (using a contiguous subregion of the geometry) is something that would benefit the text geometry as well. If the text is changed and uses less glyphs than previously allocated, the remaining unused glyphs have their sizes set to zero to make the triangles degenerate (and thus not being rendered).

**Comment by Korijn** [comment]
I would recommend to combine this work with #114 since the last remaining part there is a guide on buffers and textures.

**Comment by almarklein** [comment]
Status: I did benchmarks to look into the best approach for uploading buffer data: https://github.com/pygfx/pygfx-benchmarks/blob/main/results/bm_wgpu_buffer_upload.md#setting-data-to-a-computation-result

I want to do a few more benchmarks to get a better understanding of how chunk size affects performance. And some similar tests for textures.

**Comment by almarklein** [comment]
More benchmarks. A few in the aforementioned document. And a new series related to chunk size: https://github.com/pygfx/pygfx-benchmarks/blob/main/results/bm_wgpu_buffer_chunksize.md

Some interesting observations:
* Uploading non-contiguous data is expensive. Either a copy has to be made, or it simply hurts data transfer.
* Along the same line, indexing tricks or index-mask hurt performance a lot.
* That makes a form of chunking the most sensible approach.
* You want small chunks to have higher upload-precision. But too many chunks adds overhead.
* With a chunk-size of 1/16th the buffer size, capped at 1MB, the overhead is negligible. 
* Using `queue_write()` seems to be the best way. It outperforms other methods in quite a few situations. And I've not really found a way to leverage the flexibility of the other methods to help improve upload performance.
* These results are pretty consistent for the different hardware that I tested:
  * Mac M1
  * Intel UHD Graphics (tested same hardware via Ubuntu and Win11)
  * GeForce RTX 2070 via Win 11.

**Comment by almarklein** [comment]
I also took a quick look at structured arrays / interleaved buffers. We kinda already decided to not support this, but I wanted to explore the consequences a bit better.

Although we've already established that there is no runtime performance benefit, there is a potential use-case when all vertex data is changed interactively a lot. In such a case it would be beneficial if the data is grouped together. However, supporting this feature is complex (i.e. adds complexity and prevents certain abstractions). Both from the perspective of the engine and the API. The potential performance benefit from a pretty niche use-case don't weigh up.

**Comment by hmaarrfk** [comment]
I was hoping to have time to repeat your benchmarks with aligned arrays as an extra reference point.

we use this to allocate much of our memory since it nearly guarantees aligned memory on sane systems.

<details><summary>aligned allocator</summary>

```python
import numpy as np


def empty_aligned(shape, dtype=np.float64, align=4096):
    """Get an array with desired memory alignment.

    Parameters
    ==========
    shape: tuple of ints
        The desired final shape of the array

    dtype:
        The desired dtype of the array

    align:
        The byte alignment of the array

    Returns
    =======
    aligned_array:
        Aligned array of desired shape.

    """

    if not isinstance(shape, tuple):
        shape = (shape,)

    dtype = np.dtype(dtype)
    size = dtype.itemsize
    # Compute the final size of the array
    for s in shape:
        size *= s

    a = np.empty(size + (align - 1), dtype=np.uint8)
    data_align = a.ctypes.data % align
    offset = 0 if data_align == 0 else (align - data_align)
    arr = a[offset:offset + size].view(dtype)
    # Don't use reshape since reshape might copy the data.
    # This is the suggested way to assign a new shape with guarantee
    # That the data won't be copied.
    arr.shape = shape
    return arr
```
</details>

I don't think it will have much of an effect on integrated graphics systems (M1 + Intel UHD), but it should really speed up things with nvidia since unaligned memory transfers are forced to get copied (or so is my understanding of the landscape).

**Comment by almarklein** [comment]
### API / performance

The `gfx.Buffer` and `gfx.Texture` currently accept data that is not-contiguous. It will simply make a contiguous copy on upload. The performance loss is acceptable when the data is static, but when there is a lot of `update_range()`  calls, on large data, it may result in unnecessary overhead. In summary, convenient but possibly slow.

One solution is that the `Buffer` makes a copy when the data is given (the one at `buffer.data`. But this might be unexpected, and I don't like the idea of *sometimes* making this copy.

Another solution is for the `gfx.Buffer` to only accept contiguous data. That solves the performance issue, but puts strain on users for whom this is not an issue.

My proposal is to keep the current (convenient) approach, but in addition:
* Add performance tips in the docstring.
* Add a `high_performance` arg. When set to `True`, the buffer only accepts contiguous data, guaranteeing uploads to be "as fast as possible".

**Comment by hmaarrfk** [comment]
ps. this was a cool project that attempted to make aligning data easier using some fancy features of numpy: https://github.com/inaccel/numpy-allocator

I still do the "very basic" stuff which is to overallocate and to slice out the aligned chunk.... very silly....

**Comment by almarklein** [comment]
I think I can adjust the benchmarks quite quickly using that!

I tried on M1 and Geforce, and I see no difference: https://github.com/pygfx/pygfx-benchmarks/blob/a3951ae1f8e5dfdbe1e74d1ef2c8e8244f8ed356/benchmarks/bm_wgpu_buffer_upload.py#L292-L297

Could be that I'm missing something or that it's more hardware dependent though.

**Comment by hmaarrfk** [comment]
ok so here are some benchmarks of mine for some PCIe Gen4x4 SSDs. Some of the plots raid a few together.

Basically, once we started to "chunk data" into larger than 10MB blocks, we started to get really good performance limited nearly by the performance limits of PCIe.

At below or 1 MB, we start to really suffer from overhead somewhere (it could be the user space, the linux kernel, or the software on the SSD controller itself)

![image](https://github.com/pygfx/pygfx/assets/90008/79237e72-2a56-4688-96f9-b2a8225d44e6)

The brown line was our previous SOAT (internally) before we went down this optimization. Basically, it was slow because the kernel kept caching things..... and when you read GBs worth of stuff, you don't want the OS cache to be used at all....

We had done enough work at this time to figure out that unaligned reads were a bad idea for performance.
We really took care to invalidate the cache in all cases (our reads actually bypass the linux kernel cache otherwise it just kills performance again).
