### ISSUE TITLE
Plan for OIT

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#196]
This is a more concrete plan to solve #73. This supersedes #108 (POC via spinlock) and #174 (POC weighted blended).

## Step 1

Refactor the code such that it does two render passes, one for opaque fragments, and another for the semi-transparent fragments. In this refactoring I would like to put together the logic that defines how fragments are outputted by the shaders, so that we can also do this in different ways.

The end result will already produce better visual results, though not order-independent yet.

## Step 2

Implement weighted blended transparency (McGuire 2013), and the depth-weighted improvement (MacGuire 2016). This will make available an approach that is good enough for many use-cases.

## Step 3

Improve the result by correctly blending the first `n` layers. My initial idea was to implement a per-pixel fragment array using a spinlock, as I did in the poc in #108. However, the spinlock seems to be rather a burden, so I tried another approach that turned out to work well: use a 3d render pass to capture the foremost transparent layer.

## Necessary improvements

With the method added in step3, each object is rendered 3 times, which is a waste. We should improve performance by dividing objects into "buckets" if we know that all fragments produced by an object are either opaque or transparent. Can be done by looking at the opacity property, and by a new property set by the user.

We should also look at memory consumption of the render buffers, etc.

Some other cleanup (see todo's below).

## Possible improvements for the future

In step 3 we added a 1-layer that is properly blended, and do the rest via weighted blended. This gives sharp edges for the front-most layer, but and transitions behind that layer are not well-defined. I think that in practice this does not matter too much, because you can interact with the camera to get a better view. But of course there will be cases where this does matter. There are ways to improve on this.

One approach could be to reconsider the custom fragment buffer with spinlock again. The advantage is that it needs just two passes (the regular opaque pass, and one transparency pass), and the size of `n` only scales memory, not speed in any significant manner. The downside is that the custom RW buffer is bound to the pipeline of all wobjects. So perhaps that buffer should be shared by all renderers and be as large as the largest canvas. Anyway, this ads some complexity. The biggest hurdle though, is that we'd have to fix the glitches and incidental hanging of the spinlock.

Another approach would be to look at a hybrid depth-peeling + weighted blended. Sort of what we have, but for `n>1`. For this approach `n` will scale the number of passes. and it might need additional combination passes. On the plus side, it may re-use render targets better. With depth peeling we'd need a depth buffer attached to all wobject pipelines, so again managing this ads complexity.

## Thoughts on memory

For our renderer's internal state:

* We now have: 4B rgba, 8B picking, 4B depth -> 16 bytes per pixel.
  * With 640x480, with a pixel_ratio of 2, that is `640*480*4*16` -> 18 MiB
  * With 1920x1080, with a pixel_ratio of 2, that is `1920*1080*4*16` -> 126 MiB
* With step 2, we'd add:  8B accum, 2B revealage: 16 + 10 = 26 bytes per pixel
  * With 640x480, with a pixel_ratio of 2, that is `1920*1080*4*26` -> 30 MiB
  * With 1920x1080 with a pixel ratio of 2, that is `1920*1080*4*26` -> 206 MiB
* With step 3, we'd add another: 4B (1 color buffer): 16 + 10 + 4 = 30
  * With 640x480: 35 MiB
  * With 1920x480: 237 MiB

This is the current state at 09-12-2021. It may be possible to reduce memory consumption by re-using targets better. Also note that GPU's seem to compress the textures, because I cannot empirically replicate these numbers (see #210). 

## Remarks / ideas

* I can only use a storage-buffer for the spin-lock, but I can still use a texture for the fragments.
* Smaller spin-lock buffer by sharing a lock over multiple pixels?
* Would it help if the first pass only emits depth, and does the color in the second pass?
* What about doing the semi-transparent draw pass at reduced resolution?
* Instead of extending the 2nd pass to use a spinlock, we can also do a 3d pass for the frontmost layer.

## Todo

* [x] #198
* [x] weighted blended #204
* [x] #206
* [x] Step 4: prevent objects to render in render-passes that have no effect (buckets)
* [x] ~Split render target management out of the FragmentBlender?~
* [x ~Merge flusher into the blender?~
* [x] Use one `write_fragment()` func instead of `add_fragment()` and `finalize_fragment()`?
* [x] When writing `depth`, should it be `out.depth = ..` or something like `write_fragment_at_depth(..)`?
* [x] Better names for the blend modes?
* [x] Docstring for Renderer might need an update.
* [x] Decide what to do with z-sorting.
* [x] Update docs on examples that use flush=False, to explain that, if one is drawing to the same region, transparent objects should be drawn last. Also problematic with blend methods that clear depth in more than one pass?
* [x] Update the notes on memory above.
* [x] #209 
* [x] #208
* [x] Prevent picking depth (because it only represents the last draw).

**Comment by almarklein** [comment]
For step 4 and sorting:
* https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLRenderLists.js
​* https://github.com/mrdoob/three.js/blob/baf652649f2f0a2807c2a1065f38e060b9275aa7/src/renderers/webgl/WebGLRenderLists.js#L156
* https://github.com/mrdoob/three.js/blob/0d9851efc72c898c62e235f7346f594e5558392b/src/renderers/WebGLRenderer.js#L1120

**Comment by Korijn** [comment]
With regards to naming the blenders... We could name the approaches after their authors? I'm not sure who originally authored the simple blenders though, but the order independent onces can be named after mcguire.

**Comment by almarklein** [comment]
What we have now:
`opaque, simple1, simple2, weighted, weighted_depth, weighted_plus`
 
What we came up with in the brief brainstorm during our meeting: 
`opaque, ordered, ordered_multipass, unordered, unordered_depth, unordered_layers`

For the ordered ones, I think I like the name "ordered", but using "1" and "2" to indicate the number of passes ;)
`opaque, ordered1, ordered2, ...`

Using the author names, maybe something like this?
`..., mcguire, mcguire_depth, mcguire_plus1`

**Comment by almarklein** [comment]
Done!
