### ISSUE TITLE
Make use of float32-filterable webgpu feature

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#618]
### Background

WebGPU defines a feature called "float32-filterable". We need hardware-based linear interpolation of float textures, because scientific visualization cases often need that precision. One particular use-case is volume rendering - without linear interpolation it looks awful, and doing the interpolation in the shader (in software) strains the already heavy computation.

### Current state

In wgpu-py the feature is present in the `wgpu.FeatureName` flags, but the adapter always says it does not support it. This is because it has not been implemented downstream.

We currently use the feature "texture_adapter_specific_format_features" instead, which basically unlocks all restrictions, and thereby enables filtering for float textures. The risk of this, however, is that we may accidentally make use of other non-webgpu features, making pygfx code less portable.

### Tasks

* [x] Implement in wgpu-core. 
  * [x] https://github.com/gfx-rs/wgpu/pull/4759
* [x] Implement in wgpu-native
  * [x] https://github.com/gfx-rs/wgpu-native/pull/322 
  * [x] https://github.com/gfx-rs/wgpu-native/pull/323
  * [x] https://github.com/gfx-rs/wgpu-native/pull/332
    * Updates wgpu-native to the version of wgpu-core that has the feature.
    * Enables the feature in wgpu-native.
* [x] Update wgpu-py
  * [x] Need a release of wgpu-native that includes the feature.
  * [x] Update to that release.
* [x] Update in pygfx

**Comment by almarklein** [comment]
Closed by #644
